---
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
# load library
library(rvest)
library(ggplot2)
library(FinCal)
```

```{r echo=FALSE}
stock = "CVS"
```

```{r echo=FALSE}
# Custom Functions
# converts values to millions of $
convert <- function(x) {
  x <- gsub('[(]',"-",x)
  x <- gsub('[)]',"",x)
  if (grepl("B", x)) {
    x <- gsub('[B]',"",x) 
    x <- as.double(x)*1e3
  } else if (grepl("M", x)) {
    x <- gsub('[M]',"",x)
    x <- as.double(x) 
    x*1
  } else if (grepl("-", x)) {
    x <- gsub('-',"0",x)
    x <- as.double(x)
  }
}
```

```{r echo=FALSE}
# Scrape Financial data
income_statement <- paste0('https://www.marketwatch.com/investing/stock/',stock,'/financials')
income_statement_page <- income_statement %>% read_html()
balance_sheet <- paste0('https://www.marketwatch.com/investing/stock/',stock,'/financials/balance-sheet')
balance_sheet_page <- balance_sheet %>% read_html()
cash_flow <- paste0('https://www.marketwatch.com/investing/stock/',stock,'/financials/cash-flow')
cash_flow_page <- cash_flow %>% read_html()
more_stats <- paste0("https://finviz.com/quote.ashx?t=",stock)
more_stats_page <- more_stats %>% read_html()

income_names <- income_statement_page %>% html_nodes(".overflow__cell .fixed--cell") %>% html_text()
income_nums <- income_statement_page %>% html_nodes(".cell__content span") %>% html_text()
balance_names <- balance_sheet_page %>% html_nodes(".overflow__cell .fixed--cell") %>% html_text()
balance_nums <- balance_sheet_page %>% html_nodes(".cell__content span") %>% html_text()
cash_names <- cash_flow_page %>% html_nodes(".overflow__cell .fixed--cell") %>% html_text()
cash_nums <- cash_flow_page %>% html_nodes(".cell__content span") %>% html_text()
stats_names <- more_stats_page %>% html_nodes(".snapshot-td2-cp") %>% html_text()
stats_nums <- more_stats_page %>% html_nodes(".snapshot-td2 b") %>% html_text()

#Yearly Data 
x<-1
while (income_names[x] != "Sales/Revenue") {x<-x+1}
Revenue <- income_nums[(5*(x-1)+1):(5*x)]
for(i in 1:5){
  Revenue[i] <- convert(Revenue[i])
}
Revenue <- as.numeric(Revenue)

x<-1
while (balance_names[x] != "Total Equity") {x<-x+1}
  Equity <- balance_nums[(5*(x-1)+1):(5*x)]
for(i in 1:5){
  Equity[i] <- convert(Equity[i])
}
Equity <- as.numeric(Equity)

x<-1
while (balance_names[x] != "Long-Term Debt") {x<-x+1}
Debt <- balance_nums[(5*(x-1)+1):(5*x)]
for(i in 1:5){
  Debt[i] <- convert(Debt[i])
}
Long_Debt <- as.numeric(Debt)
DebtToEquity = Long_Debt/Equity

x<-1
while (balance_names[x] != "Short Term Debt") {x<-x+1}
Debt <- balance_nums[(5*(x-1)+1):(5*x)]
for(i in 1:5){
  Debt[i] <- convert(Debt[i])
}
Short_Debt <- as.numeric(Debt)

x<-1
while (balance_names[x] != "Total Assets") {x<-x+1}
  Assets <- balance_nums[(5*(x-1)+1):(5*x)]
for(i in 1:5){
  Assets[i] <- convert(Assets[i])
}
Assets <- as.numeric(Assets)

x<-1
while (balance_names[x] != "Total Liabilities") {x<-x+1}
  Liabilities <- balance_nums[(5*(x-1)+1):(5*x)]
for(i in 1:5){
  Liabilities[i] <- convert(Liabilities[i])
}
Liabilities <- as.numeric(Liabilities)

x<-1
while (cash_names[x] != "Free Cash Flow") {x<-x+1}
Free_Cash_Flow <- cash_nums[(5*(x-1)+1):(5*x)]
for(i in 1:5){
  Free_Cash_Flow[i] <- convert(Free_Cash_Flow[i])
}
Free_Cash_Flow <- as.numeric(Free_Cash_Flow)


#Valuation data
x<-1
while (income_names[x] != "EPS (Basic)") {x<-x+1}
EPS <- income_nums[(5*x)]
EPS <- as.double(EPS)

x<-1
while (stats_names[x] != "P/E") {x<-x+1}
PE <- stats_nums[x] %>% as.double()

x<-1
while (stats_names[x] != "Price") {x<-x+1}
price <- stats_nums[x] %>% as.double()

x<-1
while (stats_names[x] != "Dividend") {x<-x+1}
Dividend <- stats_nums[x] %>% as.double()

x<-1
while (stats_names[x] != "Dividend %") {x<-x+1}
Dividend_Percent <- stats_nums[x]
Dividend_Percent <- as.numeric(sub("%", "", Dividend_Percent))/100

x<-1
while (stats_names[x] != "Beta") {x<-x+1}
Beta <- stats_nums[x] %>% as.double()

x<-1
while (stats_names[x] != "PEG") {x<-x+1}
PEG <- stats_nums[x] %>% as.double()

x<-1
while (stats_names[x] != "Market Cap" ) {x<-x+1}
market_cap <- convert(stats_nums[x])

#market_cap <- as.numeric(gsub("[^0-9.]", "", stats_nums[x]))
#if (grepl("B", stats_nums[x])) {
#  market_cap <- market_cap * 1e9  # 1 billion
#}

x<-1
while (stats_names[x] != "Shs Outstand" ) {x<-x+1}
shsOutstanding <- convert(stats_nums[x])
```

```{r echo=FALSE}
#stats_names
#Assets[]
```


```{r echo=FALSE}
## Intrinsic Value Functions


# Discounted Cash Flow Analysis
market_debt <- function(short, long) {
  mean(tail(short, 2)) + mean(tail(long, 2))
}


dcf_analysis <- function(cash_flow) {
  
}


fm_analysis <- function(PE, PEG, EPS) {
  r = (PE/PEG)/100
  EPS * (1 + r) * PE
}

intrinsic_value <- fm_analysis(PE, PEG, EPS)


asset_based <- function(assets, liabilities, shsOutstanding) {
  (tail(Assets, 1) - tail(Liabilities, 1))/shsOutstanding
}

intrinsic_value <- asset_based(Assets, Liabilities, shsOutstanding)

```


# Stock Analysis of `r stock`

## Plots

### Revenue Plot  
```{r, echo=FALSE}
df <- data.frame (
  year = 1:5,
  Revenue = Revenue,
  DebtToEquity = DebtToEquity,
  Free_Cash_Flow = Free_Cash_Flow
)
```
```{r echo=FALSE}
graph <- function(data,col,ylabel) {
    ggplot(df, aes(year,data)) +
      geom_bar(stat="identity", width = 0.8, fill = col, color = "black", alpha = 0.8) +
      #geom_smooth(method=lm, se=FALSE, size=2) +
      geom_text(aes(label=data), vjust = -0.3) +
      ylab(ylabel) +
      theme_bw()
}

graph(Revenue, "blue","Revenue in Millions of $")

```


### Free Cash Flow Plot  

```{r echo=FALSE}
graph(Free_Cash_Flow, "green","Free Cash Flow in Millions of $")
```

### Debt-to-Equity Ratio Plot  
```{r, echo=FALSE, warning=FALSE, message=FALSE}
ggplot(df, aes(year, DebtToEquity)) +
  geom_smooth(col = "#B80F0A") +
  #geom_line(col="#B80F0A", size = 2) +
  geom_point(size=4, col="#B80F0A") +
  geom_text(label=round(DebtToEquity,2), y=DebtToEquity+.07) +
  geom_hline(yintercept = 1) +
  annotate("text", x=2, y=1.05, label='"Good" Debt to Equity') +
  ylim(0,max(1.5,DebtToEquity)) +
  theme_bw()
```

## Price Valuations

**Current Price:** `r price`  
**Financial Metric Valuation:** `r round(fm_analysis(PE, PEG, EPS),2)`  
**Asset Based Valuation:** `r round(asset_based(Assets, Liabilities, shsOutstanding),2)`

